FROM python:3.10
RUN mkdir /code
WORKDIR /code
COPY DemoFastApi/. /code/
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
